Тема “Вычисления с помощью Numpy”

Задание №1

In [20]:
import numpy as np

In [21]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])

In [22]:
at = a.transpose()

In [23]:
at

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [25]:
mean_a = at.mean(axis = 0)

In [26]:
mean_a

array([2. , 8.4])

Задание №2

In [31]:
a_centered = at - mean_a

In [32]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание №3

In [45]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])

In [48]:
a_centered_sp

8.0

In [53]:
N = at.shape[0]

In [54]:
N

5

In [58]:
N_cov = a_centered_sp / (N - 1)

In [59]:
N_cov

2.0

Задание №4

In [62]:
np.cov(a_centered.transpose())

array([[1. , 2. ],
       [2. , 4.3]])

Тема “Работа с данными в Pandas”

Задание №1

In [67]:
import numpy as np
import pandas as pd

In [71]:
authors = pd.DataFrame({'author_id':[1, 2, 3], 
                   'author_name':['Тургенев', 'Чехов', 'Островский']}, 
                  columns=['author_id', 'author_name'])

In [72]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [73]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3], 
                   'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                    'price':[450, 300, 350, 500, 450, 370, 290]}, 
                  columns=['author_id', 'book_title', 'price'])

In [74]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание №2

In [75]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'outer')

In [76]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Задание №3

In [77]:
top5 = authors_price.nlargest(5, 'price')

In [78]:
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

Задание №4

In [123]:
authors_stat = authors_price.groupby('author_name').agg({'price':['min','max','mean']}).round(2)

In [124]:
authors_stat

price             
              min  max    mean
author_name                   
Островский    290  370  330.00
Тургенев      300  450  366.67
Чехов         450  500  475.00

Задание №5

In [127]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [128]:
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [136]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'], columns=['cover'], aggfunc=np.sum, fill_value=0)

In [137]:
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [138]:
book_info.to_pickle('book_info.pkl')

In [139]:
book_info2 = pd.read_pickle('book_info.pkl')

In [141]:
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [142]:
book_info == book_info2

cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев       True     True
Чехов          True     True