In [1]:
import numpy as np
import pandas as pd

Задание №1

In [4]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Задание №2

In [6]:
a1 = a.reshape(2, 6)
print(a1)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [7]:
a2 = a.reshape(3, 4)
print(a2)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [8]:
a3 = a.reshape(4, 3)
print(a3)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [9]:
a4 = a.reshape(6, 2)
print(a4)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [10]:
a5 = a.reshape(12, 1)
print(a5)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


Задание №3

In [11]:
a1 = a.reshape(2, -1)
print(a1)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [12]:
a2 = a.reshape(3, -1)
print(a2)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [13]:
a3 = a.reshape(4, -1)
print(a3)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [14]:
a4 = a.reshape(-1, 2)
print(a4)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [15]:
a5 = a.reshape(-1, 1)
print(a5)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


Задание №4

НЕЛЬЗЯ

Задание №5

In [17]:
rm = np.random.randn(3, 4)
rm

array([[ 0.51691131,  0.19089304,  0.0720048 , -0.00540194],
       [-0.79192153, -1.78083279,  0.43458577, -0.96097629],
       [-0.15540887,  0.66190079,  0.31243366, -0.18696973]])

In [18]:
rm1 = rm.flatten()
rm1

array([ 0.51691131,  0.19089304,  0.0720048 , -0.00540194, -0.79192153,
       -1.78083279,  0.43458577, -0.96097629, -0.15540887,  0.66190079,
        0.31243366, -0.18696973])

In [19]:
print(rm.size)
print(rm1.size)

12
12


Задание №6

In [21]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Задание №7

In [23]:
b = np.arange(20, 0, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Массив a - одномерный массив, а Массив b - двумерный массив

Задание №8

In [24]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [25]:
print(a.size)

4


In [26]:
b = np.zeros((3, 2)) +1
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
print(b.size)

6


In [28]:
c = np.vstack((a, b))
c

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
print(c.size)

10


Задание №9

In [30]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [34]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [35]:
B.shape

(4, 4)

In [36]:
B_reverse = np.linalg.inv(B)
B_reverse

LinAlgError: Singular matrix

Вычислить обратную матрицу для матрицы B невозможно.

Задание №10

In [38]:
np.random.seed(42)

Задание №11

In [41]:
a = np.random.randint(0, 16,16)
a

array([ 3,  7,  7,  2,  5,  4,  1,  7, 11, 13,  5,  1, 15, 11,  4,  0])

Задание №12

In [44]:
C = a.reshape(4, 4)
C

array([[ 3,  7,  7,  2],
       [ 5,  4,  1,  7],
       [11, 13,  5,  1],
       [15, 11,  4,  0]])

In [45]:
D = B + C * 10
D

array([[ 35,  84,  93,  52],
       [ 64,  90,  96, 192],
       [133, 216, 199, 222],
       [182, 232, 252, 302]])

In [46]:
d = np.linalg.det(D)
d

-23405000.00000006

In [47]:
r = np.linalg.matrix_rank(D)
r

4

In [48]:
D_inv=np.linalg.inv(D)
D_inv

array([[-0.02745824, -0.02127921, -0.00030506,  0.01848067],
       [-0.00983038, -0.00115445,  0.03006537, -0.01967443],
       [ 0.03091391,  0.00259603, -0.0266755 ,  0.01263576],
       [-0.00169622,  0.01154454, -0.00065371, -0.00325571]])

Задание №13

In [49]:
D_inv = np.where(D_inv<0, 0, 1)
D_inv

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 1, 0, 1],
       [0, 1, 0, 0]])

In [50]:
print(B)
print(C)
E = np.where(D_inv == 1, B, C)
E

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 3  7  7  2]
 [ 5  4  1  7]
 [11 13  5  1]
 [15 11  4  0]]


array([[  3,   7,   7,  32],
       [  5,   4,  86,   7],
       [ 23,  86,   5, 212],
       [ 15, 122,   4,   0]])